sudo: false
language: node_js
matrix:
  include:
    - node_js: '6'
    - node_js: '8'
    - node_js: '9'

after_success:
  - cat ./coverage/coverage.json | ./node_modules/.bin/adana -F adana-format-istanbul > ./coverage/istanbul.json
  - bash <(curl -s https://codecov.io/bash) -f ./coverage/istanbul.json
