sudo: false
language: node_js
matrix:
  include:
    - node_js: '4'
    - node_js: '6'
    - node_js: '8'

after_script:
  - npm install coveralls
  - cat ./coverage/coverage.json | ./node_modules/.bin/adana --format lcov | ./node_modules/coveralls/bin/coveralls.js
